### ISSUE TITLE
Bot Refactor

### ISSUE THREAD

**Issue by valkyrienyanko** [TheSheepGuy/open-lilybot#1]
Your events could be in a folder of their own. Let me know if you want me to create a PR and I'll get started first chance I get.

e.g. client.on('ready') could be in a file called ready.js in a folder called events.

**Comment by TheSheepGuy** [comment]
That seems quite sensible, particularly the on("message") part. Feel free to do so!

**Comment by valkyrienyanko** [comment]
Done. See #2
